openapi: 3.0.3
info:
  title: SallyContractTesting
  version: 1.0.0
  contact: {}
servers:
  - url: https://api.admin.stg.supplyally.gov.sg
paths:
  /userLocationRoles:
    get:
      summary: /userLocationRoles
      description: /userLocationRoles
      operationId: userlocationroles
      parameters:
        - name: Cookie
          in: header
          schema:
            type: string
            example: >-
              token=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4OTYwMzNhZC0yYzcwLTRkNmMtOTY1Ny1mZWVlOWE0OGQxOTUiLCJzZXNzaW9uSWQiOiI4MjhjMDkyOC0xNTE1LTQyZWQtYmJkOS1jM2Q4OTBhOTBlMDkiLCJleHAiOjE2ODA3OTUyNjUsImlhdCI6MTY4MDc5MTY2NX0.diE_CJjg1aI0g7CNlLNc-9Q-J0Bqj5CtC0hB5JYIC1WI4Ooi5aE06OsQaEy2ChxF_HeNH2dYSDvMJtREfkJV3Q
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: b24f2bac-e5d1-4961-9c1a-3c82195cafc0
            example:
              userId: b24f2bac-e5d1-4961-9c1a-3c82195cafc0
      responses:
        '200':
          description: ''
tags: []
